"""empty message

Revision ID: 48015e9f1572
Revises: edb95727ef7e
Create Date: 2017-02-27 23:46:55.577866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48015e9f1572'
down_revision = 'edb95727ef7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
